[build]
builder = "NIXPACKS"
# Aquí obligamos a Nixpacks a instalar Node.js en el servidor
providers = ["node"]
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd frontend && npx serve -s build -l $PORT"
restartPolicyType = "ON_FAILURE"